### ISSUE TITLE
Including map controls

### ISSUE THREAD

**Issue by aratcliffe** [mapbox/leaflet-image#34] opened 2014-12-08 01:50 UTC
Hi, I'm wondering about the feasibility of being able to include map controls such as the scale control in the output image. Is this something you've thought about?

**Comment by tmcw** [comment] 2014-12-08 14:53
Duplicate of #24: barring a cross-browser API that rasterizes HTML, this is not possible.

**Closed as completed by tmcw** 2014-12-08 14:53 UTC
Labels: readme-unread
