### ISSUE TITLE
It does not work with non-map images

### ISSUE THREAD

**Issue by diegofal** [mapbox/leaflet-image#94] opened 2017-02-14 01:07 UTC
Hello, and thank you for this tool!
 I am trying to use it with a non-map (no tiles) image. 
 So the the image is a single file image loaded using leafletjs.

 Apparently, the code looks only for L.TileLayer. If this is not the case, it will ignore the main map image.
 The rest of the layers are copied successfully.

Any thoughts ?
Thanks!

**Comment by tmcw** [comment] 2017-02-14 01:08
Is it a L.ImageOverlay? If so, this is a duplicate of #59. If not, what specific type of layer is it?

**Comment by diegofal** [comment] 2017-02-14 09:28
Yes, it is the base layer, which is basically a L.ImageOverlay (single tile)
Will take a look at those duplicates and see if there is a solution. If so, I will close this one.

Thanks!

**Closed as completed** 2017-03-14 20:09 UTC
