### ISSUE TITLE
Bower install

### ISSUE THREAD

**Issue by ghost** [mapbox/leaflet-image#56] opened 2016-02-15 20:38 UTC
Hi, any chance of having this plugin registered with Bower?

I can do a Pull request for a bower.json file to be included with the repository if needed.

**Comment by tmcw** [comment] 2016-02-15 20:43
Duplicate of https://github.com/mapbox/leaflet-image/issues/50 - please use a system other than Bower.

**Closed as completed by tmcw** 2016-02-15 20:43 UTC

**Comment by ghost** [comment] 2016-02-15 20:47
I apologize for the duplicate question, should've searched the closed issues.
