### ISSUE TITLE
Regression in "1.0 compat" PR: Tiles don't scale properly in 

### ISSUE THREAD

**Issue by dbazile** [mapbox/leaflet-image#66] opened 2016-04-13 03:08 UTC
I introduced a regression with https://github.com/mapbox/leaflet-image/pull/65.  Didn't find this until I fully integrated it into my app and _really_ started poking at it. 😞 
### Problem

Works fine in a sandbox that zooms in VERY close to a given feature, but as you zoom out the tile positioning drifts further and further out of whack.  Occasionally, tiles that appear at the edges will also fall out of the frame, leaving big gaps of transparency.

<img width="674" alt="screen shot 2016-04-12 at 11 04 13 pm" src="https://cloud.githubusercontent.com/assets/1542531/14481661/2c59c1b8-0103-11e6-99d8-83ab7e0e70fc.png">
### Scope
- Leaflet 1.0.0-beta2
- Retina and non-Retina screens

I've included a [jsfiddle demonstrating the problem](https://jsfiddle.net/bazile/by3eb5mv/24/) just in case.

**Comment by BenjaminVadant** [comment] 2016-07-07 13:11
Hi,
due to this bug, I looked into a way to "not" using your plugin with leaflet v1.0. And I created this snippet : https://jsfiddle.net/auj7L750/3/

Which actually does the job in chrome 51 and Firefox 35.

It might not be the solution but at least part of it!

Enjoy!

Ben

**Comment by rgtaylor1989** [comment] 2016-07-28 16:59
Has anyone looked into this problem? 

I've managed to locate where the problem is but I have no idea how to fix it. 

using the fiddle (https://jsfiddle.net/bazile/by3eb5mv/24/) the tiles are not misaligned if the container "leaflet-tile-container" has translate3d set to 0px, 0px, 0px ... when you zoom out or in the translate3d style moves to reflect the new animation and is no longer at the top left corner at 0px, 0px, 0px (this is different than previous versions of leaflet that always used the top left corner). The tiles are drawn from this new point so when an image is exporting, leaflet-image is trying to draw from 0px,0px,0px instead of the new point. To see this in action, zoom the map and make sure the container that contains the tiled images 3dtranslate changed from 0px,0px,0px and click export. The image should be misaligned with the canvas. Changing the 3dtranslate back to 0px,0px,0px in the html structure shifts the tiles but should match the exported drawing.

Perhaps we could shift the tiles being drawn by the new point?

**Comment by rgtaylor1989** [comment] 2016-07-29 16:17
Taken from https://github.com/MichaelHu/leaflet-image/commit/291e39fc1f9c717cd12172bd99f4c2ae322e4063

_Solution_
around line 109:
var tilePos = originalTilePoint.scaleBy(new L.Point(tileSize, tileSize)).subtract(bounds.min);

This fixes the regression.

**Comment by sainsb** [comment] 2016-10-06 18:34
I just dumped so many hours into fighting this... @rgtaylor1989 **thank you** -- your solution worked

**Comment by zulfahmi** [comment] 2016-12-01 08:15
Aaah Thank you @rgtaylor1989 , it works

**Comment by tmcw** [comment] 2016-12-05 20:16
Ported the fix in 71043d986f90e66f4c35607d4e02d8e791621e61 and released as 0.4.0.

**Closed as completed by tmcw** 2016-12-05 20:16 UTC
